apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
#  type: ClusterIP
  type: NodePort
  selector:
    project: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.container.port }}
      targetPort: 8080
      nodePort: {{ .Values.container.nodePort }}

