openapi: 3.0.2
info:
  description: "This is call state changer adapter API"
  title: Call state changer API
  version: 0.1.0

servers:
  - url: '{protocol}://{server}:{port}'
    variables:
      protocol:
        enum:
          - 'http'
        default: 'http'
      server:
        default: 'localhost'
      port:
        enum:
          - '80'
        default: '80'

tags:
  - name: Call state
    description: Allows to control state of the call

paths:
  "/v1/calls":
    post:
      tags:
        - Call state
      operationId: createCall
      description: start a new call

      requestBody:
        $ref: '#/components/requestBodies/Call'

      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AcceptedResponse"
        "400":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  "/v1/calls/{callId}:delete":
    post:
      tags:
        - Call state
      operationId: deleteCall
      description: end call

      parameters:
        - $ref: '#/components/parameters/callId'

      responses:
        "202":
          description: Accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AcceptedResponse"
        "400":
          description: Bad input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  parameters:
    callId:
      name: callId
      description: "The unique 36 character id that represents the call"
      required: true
      in: path
      schema:
        type: string
        minLength: 36
        maxLength: 36
        example: "bea76b16-5aff-4cd6-8db0-5d8d649dd865"
  requestBodies:
    Call:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Call'
      required: true
      description: call metadata

  schemas:
    Call:
      type: object
      required:
        - id
        - callerNumber
        - calledNumber
        - participant
        - timestamp
      properties:
        id:
          type: string
          description: call id
        callerNumber:
          type: string
          description: phone number of the caller
        calledNumber:
          type: string
          description: dialed phone number
        engagementDialogId:
          type: string
          description: A Media Platform specific identifier for the engagement dialog on which to initialize
        participant:
          $ref: "#/components/schemas/Participant"
        timestamp:
          type: string
          format: date-time
          description: timestamp

    Participant:
      type: object
      description: calling participant
      required:
        - id
      properties:
        id:
          type: string
          description: participant id
        name:
          type: string
          description: participant autodetected name

    ErrorResponse:
      type: object
      required:
        - code
        - message
        - detail
        - timestamp
      properties:
        code:
          type: string
          description: Error code that identifies the unexpected condition
        message:
          type: string
          description: Human readable error message
        details:
          type: string
          description: Detailed error message describing the cause
        timestamp:
          type: string
          format: date-time
          description: Error timestamp

    AcceptedResponse:
      type: string
      description: Message to confirm that reqest accepted succesfull
